name: Ansible deploy

on: [push]
  workflow_dispatch:
jobs:
  build:


    runs-on: [self-hosted, linux]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7,
      uses: actions/setup-python@v1
      with:
        python-version: 3.7 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible==2.9.2 requests
   
    - name: run playbook
      run: |
        ansible-playbook  --connection=local --inventory 127.0.0.1, ansible-playbook.yml



 



