# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.


name: Ansible deploy auto 

on: [push]
  
jobs:
  build:


    runs-on: [self-hosted, linux]


    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8,
      uses: actions/setup-python@v3
      uses: ./.github/actions/
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible==2.9.2 requests

      env:
        VAULT_PASS: ${{ secrets.VAULT_PASS }}
    - name: run playbook
      run: |
        ansible-playbook  --inventory 127.0.0.1, ansible-playbook.yml



 




