# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.


name: Ansible deploy auto 

on: [push]
  
jobs:
  build:


    runs-on: [self-hosted, linux]
    #needs: build # The build job should finished successfully.
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8,
      uses: actions/setup-python@v3
    
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible==2.9.2 requests
   
    - name: set ansible config secrets   
      env:
        VAULT_PASS: ${{ secrets.VAULT_PASS }}
        SSH_KEY: ${{ secrets.SSH_KEY }}

      run: |
        echo "$VAULT_PASS" > .ansible-vault-password
        mkdir .ssh
        echo "$SSH_KEY" > .ssh/id_RSA
        chmod 600 .ssh/id_RSA

    - name: checkout repo
      uses: actions/checkout@v2
    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@master
      with:
        targets: ""
        
    - uses: actions/checkout@v1
    - uses: ./.github/actions/ansible
      with: 
        playbook: ansible-playbook.yml
        inventory: localhost


        


