# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.


name: Ansible deploy auto 

on: [push]
  
jobs:
  build:


    runs-on: [self-hosted, linux]
    #needs: build # The build job should finished successfully.
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions
        env:
          VAULT_PASS: ${{ secrets.VAULT_PASS }}

   

   



